// <auto-generated />
using MOD.TechnologyService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MOD.TechnologyService.Migrations
{
    [DbContext(typeof(TechnologyContext))]
    partial class TechnologyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MOD.TechnologyService.Models.Technology", b =>
                {
                    b.Property<int>("Tech_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TOC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tech_Duration")
                        .HasColumnName("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Tech_Fees")
                        .HasColumnName("Fees")
                        .HasColumnType("int");

                    b.Property<string>("Tech_name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Tech_id");

                    b.ToTable("Technology");
                });
#pragma warning restore 612, 618
        }
    }
}
